services:
  frontend:
    build:
      context: ./Desafio-WEB-Frontend
    container_name: desafiocriar-frontend
    ports:
      - "5174:5174"
    command: ["npm", "run", "dev", "--", "--host=0.0.0.0", "--port=5174"]
    depends_on:
      - backend

  backend:
    build:
      context: ./Desafio-WEB-Backend
    container_name: desafiocriar-backend
    ports:
      - "8000:8000"
    volumes:
      - ./Desafio-WEB-Backend:/var/www
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: grupo_criar
      DB_USERNAME: usuario
      DB_PASSWORD: senha123
    command:
      [
        "sh",
        "-c",
        "php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=8000",
      ]
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: desafiocriar-postgres
    restart: always
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: grupo_criar
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha123
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: desafiocriar-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  pgdata:
